# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23b5ef323603dd38a1f59073d17cfd94b82b50dec8f65ee0e7c6dec260161f52d4aeff928d4b916e8e3b74d8b559202782bef96c3c565a638f9be874948b1553

test:
  secret_key_base: cc02b7d28b9440b6916b2c76b378e0b28ff08e5f670228c6a88635a11cf2159983cc72f5adc54fcfdc0e9ce0506ef9a51726ab471c52f5ad7e2dbc52073a155d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
